[package]
name = "secret-sharing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chacha20poly1305 = "0.10"
clap = { version = "4.0", features = ["derive"] }
hex = "0.4"
rand = "0.8"
shamirsecretsharing = "0.1"
